apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crypto-rates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-crypto-rates
  template:
    metadata:
      labels:
        app: my-crypto-rates
    spec:
      containers:
      - name: my-crypto-rates
        image: my-crypto-rates:latest
        ports:
        - containerPort: 3000
